title: 'Buchhaltung & Verwaltung'
team_tag_type: dark
filter_category: management
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1670951716
blueprint: team_tags
localizations:
  en:
    title: 'Accounting & Administration Manager'
    slug: buchhaltung-und-verwaltung
    updated_by: 5c84a3c2-1f9f-4c46-ace2-d9eaf068d261
    updated_at: 1686045807
