title: 'Büroleitung & Finanzen'
team_tag_type: dark
filter_category: management
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1657210911
blueprint: team_tags
localizations:
  en:
    title: 'finance and office manager'
    slug: bueroleitung-und-finanzen
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657210915
