title: Kommunikation
team_tag_type: dark
filter_category: management
updated_by: 7d709850-5c35-4065-be68-b627c348051d
updated_at: 1657807933
blueprint: team_tags
localizations:
  en:
    title: communication
    slug: kommunikation-und-projektassistenz
    updated_by: 5c84a3c2-1f9f-4c46-ace2-d9eaf068d261
    updated_at: 1686045720
