title: 'Marketing & Fundraising'
team_tag_type: dark
filter_category: management
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1657210942
blueprint: team_tags
localizations:
  en:
    title: 'marketing and fundraising'
    slug: marketing-und-fundraising
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657212070
