title: Education
team_tag_type: dark
filter_category: management
updated_by: b89f1882-9bbc-44b7-9265-79a3230c2164
updated_at: 1737032211
blueprint: team_tags
localizations:
  en:
    title: 'project manager & press contact'
    slug: projektleitung-und-presse
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657211032
