title: Regie/Choreografie/Szenographie
team_tag_type: dark
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1699289869
blueprint: team_tags
localizations:
  en:
    title: 'Stage Director'
    slug: regie-choreografie
    updated_by: 5c84a3c2-1f9f-4c46-ace2-d9eaf068d261
    updated_at: 1686045735
