title: Trompete
team_tag_type: green
filter_category: blechblasinstrumente
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1657211257
blueprint: team_tags
localizations:
  en:
    title: trumpet
    slug: trompete
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1657211265
