title: Violine
updated_by: 7d709850-5c35-4065-be68-b627c348051d
updated_at: 1656611467
blueprint: team_tags
team_tag_type: green
filter_category: streichinstrumente
localizations:
  en:
    title: Violin
    slug: violine
    updated_by: 5c84a3c2-1f9f-4c46-ace2-d9eaf068d261
    updated_at: 1686045398
