title: Holzblasinstrumente
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1670951991
blueprint: instrumenten_gruppen
localizations:
  en:
    title: Woodwinds
    slug: holzblasinstrumente
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1670952058
