title: Rhythmusinstrumente
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1670952135
blueprint: instrumenten_gruppen
localizations:
  en:
    title: 'Rhythm section'
    slug: rhythmusinstrumente
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1670952153
