title: 'Künstlerischer Beirat'
updated_by: 7d709850-5c35-4065-be68-b627c348051d
updated_at: 1656611120
blueprint: team_filters
localizations:
  en:
    title: 'artistic direction'
    slug: kuenstlerischer-beirat
    updated_by: 7d709850-5c35-4065-be68-b627c348051d
    updated_at: 1656611237
