title: Rhythmusinstrumente
updated_by: 7d709850-5c35-4065-be68-b627c348051d
updated_at: 1656611146
blueprint: team_filters
localizations:
  en:
    title: 'Rhythm section'
    slug: rhythmusinstrumente
    updated_by: 7d709850-5c35-4065-be68-b627c348051d
    updated_at: 1656611255
