title: Management
updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
updated_at: 1670952198
blueprint: personen_funktionen
localizations:
  en:
    title: Management
    slug: management
    updated_by: f6128d7d-0471-44e5-b89a-e3213d7a0925
    updated_at: 1670952209
